import { useEffect, useRef } from 'react';
import { X, Printer, Download, FileText } from 'lucide-react';
import { SoapNote, Vitals } from '@/types/clinical';

interface PreviewNoteModalProps {
  isOpen: boolean;
  onClose: () => void;
  note: SoapNote;
  patientName: string;
  patientId: string;
  sessionDate: string;
  vitals: Vitals;
}

const sections: { key: keyof SoapNote; label: string; color: string }[] = [
  { key: 'subjective', label: 'S — Subjective', color: 'text-blue-700' },
  { key: 'objective', label: 'O — Objective', color: 'text-green-700' },
  { key: 'assessment', label: 'A — Assessment', color: 'text-purple-700' },
  { key: 'plan', label: 'P — Plan', color: 'text-orange-700' },
];

function printNote(patientName: string, patientId: string, sessionDate: string, vitals: Vitals, note: SoapNote) {
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Clinical Note — ${patientName}</title>
      <style>
        body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #111; font-size: 13px; line-height: 1.7; }
        h1 { font-size: 18px; margin-bottom: 4px; }
        .meta { color: #555; font-size: 12px; margin-bottom: 20px; }
        .vitals { background: #f8f8f8; border: 1px solid #ddd; border-radius: 6px; padding: 10px 16px; margin-bottom: 20px; display: flex; gap: 24px; }
        .vital-item { font-size: 12px; } .vital-item strong { display: block; font-size: 11px; text-transform: uppercase; color: #666; }
        .section { margin-bottom: 18px; }
        .section-label { font-weight: bold; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #444; border-bottom: 1px solid #eee; padding-bottom: 4px; margin-bottom: 6px; }
        .section-body { white-space: pre-wrap; color: #222; }
        .empty { color: #aaa; font-style: italic; }
        .footer { margin-top: 40px; border-top: 1px solid #ddd; padding-top: 12px; font-size: 11px; color: #888; }
      </style>
    </head>
    <body>
      <h1>Clinical Encounter Note</h1>
      <p class="meta">Patient: <strong>${patientName}</strong> &nbsp;|&nbsp; ID: ${patientId} &nbsp;|&nbsp; Date: ${sessionDate}</p>
      <div class="vitals">
        <div class="vital-item"><strong>Blood Pressure</strong>${vitals.bloodPressure || '—'}</div>
        <div class="vital-item"><strong>Heart Rate</strong>${vitals.heartRate || '—'}</div>
        <div class="vital-item"><strong>Temperature</strong>${vitals.temperature || '—'}</div>
      </div>
      ${sections.map(s => `
        <div class="section">
          <div class="section-label">${s.label}</div>
          <div class="section-body">${note[s.key]?.trim() ? note[s.key].replace(/</g,'&lt;').replace(/>/g,'&gt;') : '<span class="empty">Not documented</span>'}</div>
        </div>
      `).join('')}
      <div class="footer">Generated by PracticeFlow CRM &nbsp;·&nbsp; ${new Date().toLocaleString()}</div>
    </body>
    </html>
  `;
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(content);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); }, 400);
  }
}

function exportNote(patientName: string, patientId: string, sessionDate: string, vitals: Vitals, note: SoapNote) {
  const lines = [
    `CLINICAL ENCOUNTER NOTE`,
    `========================`,
    `Patient: ${patientName}`,
    `ID:      ${patientId}`,
    `Date:    ${sessionDate}`,
    ``,
    `VITALS`,
    `------`,
    `Blood Pressure : ${vitals.bloodPressure || '—'}`,
    `Heart Rate     : ${vitals.heartRate || '—'}`,
    `Temperature    : ${vitals.temperature || '—'}`,
    ``,
    ...sections.flatMap(s => [
      ``,
      s.label.toUpperCase(),
      `${'-'.repeat(s.label.length)}`,
      note[s.key]?.trim() || '(Not documented)',
    ]),
    ``,
    `Generated: ${new Date().toLocaleString()}`,
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `clinical-note_${patientName.replace(/[^a-z0-9]/gi, '-')}_${sessionDate}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function PreviewNoteModal({
  isOpen,
  onClose,
  note,
  patientName,
  patientId,
  sessionDate,
  vitals,
}: PreviewNoteModalProps) {
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isOpen) return;
    function onKey(e: KeyboardEvent) { if (e.key === 'Escape') onClose(); }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <div
        ref={modalRef}
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl border border-gray-200 flex flex-col max-h-[90vh]"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-gray-100 px-6 py-4 shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-teal-500 to-emerald-600">
              <FileText className="h-4 w-4 text-white" />
            </div>
            <div>
              <h2 className="text-base font-bold text-gray-900">Note Preview</h2>
              <p className="text-xs text-gray-400">Read-only · {sessionDate}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-xl p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Body */}
        <div className="overflow-y-auto px-6 py-5 flex-1">
          {/* Patient + vitals header */}
          <div className="mb-5 rounded-xl border border-slate-100 bg-slate-50 p-4">
            <p className="text-sm font-bold text-gray-900">{patientName}</p>
            <p className="text-xs text-gray-500 mb-3">ID: {patientId} · {sessionDate}</p>
            <div className="flex gap-4 flex-wrap">
              {[
                { label: 'Blood Pressure', val: vitals.bloodPressure },
                { label: 'Heart Rate', val: vitals.heartRate },
                { label: 'Temperature', val: vitals.temperature },
              ].map(({ label, val }) => (
                <div key={label} className="flex flex-col">
                  <span className="text-[10px] uppercase tracking-wider text-gray-400 font-semibold">{label}</span>
                  <span className="text-sm font-semibold text-gray-800">{val || '—'}</span>
                </div>
              ))}
            </div>
          </div>

          {/* SOAP sections */}
          <div className="flex flex-col gap-4">
            {sections.map((section) => (
              <div key={section.key} className="rounded-xl border border-gray-100 p-4">
                <p className={`text-xs font-bold uppercase tracking-widest mb-2 ${section.color}`}>
                  {section.label}
                </p>
                <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                  {note[section.key].trim() || (
                    <span className="italic text-gray-400">Not documented</span>
                  )}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Footer actions */}
        <div className="flex items-center justify-between border-t border-gray-100 px-6 py-4 shrink-0">
          <button
            onClick={onClose}
            className="rounded-xl px-4 py-2 text-sm text-gray-500 hover:bg-gray-100 transition-colors"
          >
            Close
          </button>
          <div className="flex items-center gap-2">
            <button
              onClick={() => exportNote(patientName, patientId, sessionDate, vitals, note)}
              className="flex items-center gap-1.5 rounded-xl border border-gray-200 px-4 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              Export .txt
            </button>
            <button
              onClick={() => printNote(patientName, patientId, sessionDate, vitals, note)}
              className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-teal-600 to-emerald-600 px-4 py-2 text-xs font-semibold text-white shadow-sm hover:from-teal-700 hover:to-emerald-700 transition-all"
            >
              <Printer className="h-3.5 w-3.5" />
              Print
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}